### ISSUE TITLE
This extension is not hiding reactions.

### ISSUE THREAD

**Issue by luvittor** [kortaggio/HideTheLikes#3]
btw, thank you! :+1:

**Comment by kortaggio** [comment]
I'm aware that reactions are showing up in the notification area, but they are properly hidden in the newsfeed. Can you share a screenshot of anywhere else reactions are showing up?

**Comment by kortaggio** [comment]
Forcing a `display: none` in any case a41bb56594662315f55fb17b24d42769c99eadac
